# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('phone_contact', models.CharField(max_length=50, null=True)),
                ('name_contact', models.CharField(max_length=200, null=True)),
                ('email_contact', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(upload_to='uploads/marks/')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('phone_contact', models.CharField(max_length=50, null=True)),
                ('name_contact', models.CharField(max_length=200, null=True)),
                ('email_contact', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(upload_to='uploads/retail/')),
            ],
        ),
    ]
