# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-07 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_provider', models.CharField(choices=[('0', 'Marca'), ('1', 'Retail')], default='0', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('phone_contact', models.CharField(max_length=50, null=True)),
                ('name_contact', models.CharField(max_length=200, null=True)),
                ('email_contact', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(upload_to='uploads/marks/')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='Retail',
        ),
    ]
