# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-06 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20170705_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['name'], 'verbose_name': 'Promoci\xf3n', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.AddField(
            model_name='bond',
            name='shopy_value',
            field=models.CharField(default=1, max_length=200, verbose_name='Numero de shoppy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n'),
        ),
    ]
