# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-07 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='web_site',
            field=models.CharField(max_length=255, null=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email_contact',
            field=models.CharField(max_length=200, null=True, verbose_name='Email contacto'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name_contact',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre contacto'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_contact',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefono contacto'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='type_provider',
            field=models.CharField(choices=[('0', 'Marca'), ('1', 'Retail')], default='0', max_length=200, verbose_name='Tipo'),
        ),
    ]
