# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-07 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_auto_20170607_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email_contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email contacto'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='img',
            field=models.ImageField(upload_to='uploads/marks/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name_contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre contacto'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono contacto'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sitio web'),
        ),
    ]
