# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20170607_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('value', models.CharField(max_length=200, verbose_name='Valor')),
                ('code', models.CharField(max_length=200, verbose_name='Codigo')),
                ('status', models.CharField(choices=[('0', 'Activo'), ('1', 'Redimido')], default='0', max_length=200, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Bono',
                'verbose_name_plural': 'Bonos',
                'ordering': ['name'],
            },
        ),
    ]
