# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_bond'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='bond',
            name='description',
            field=models.TextField(default=1, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
