# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_auto_20170608_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='providers.Provider'),
            preserve_default=False,
        ),
    ]
