# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_promotion_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='providers.Provider', verbose_name='Marca o Retail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Provider', verbose_name='Marca o Retail'),
        ),
    ]
