# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-20 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20170608_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads/promotion/', verbose_name='Imagen'),
        ),
    ]
