# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-27 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_promotion_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads/bond/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='provider',
            name='value_bond1',
            field=models.CharField(default=1, max_length=200, verbose_name='Valor del bono 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='value_bond2',
            field=models.CharField(default=1, max_length=200, verbose_name='Valor del bono 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='value_bond3',
            field=models.CharField(default=1, max_length=200, verbose_name='Valor del bono 3'),
            preserve_default=False,
        ),
    ]
