# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_auto_20170627_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['name'], 'verbose_name': 'Promociion', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.AlterField(
            model_name='bond',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
