# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('mensaje', models.CharField(max_length=255, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Mensaje de la aplicación',
                'verbose_name_plural': 'Mensajes de la aplicación',
                'ordering': ['pk'],
            },
        ),
    ]
