# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
        ('products', '0002_auto_20170606_1322'),
    ]

    operations = [
    ]
