# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shopper_points',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='xperience',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
