# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bornday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shopper_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='xperience',
        ),
    ]
