# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-06 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20170706_1653'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, null=True)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Bond', verbose_name='Bonos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name': 'Redencion',
                'verbose_name_plural': 'Redenciones',
            },
        ),
    ]
