# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_redemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='code',
            field=models.IntegerField(default=1, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redemption',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='redemption',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='bond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos', to='providers.Bond', verbose_name='Bonos'),
        ),
    ]
