# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170606_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bornday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shopper_points',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='xperience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
