# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_task_name'),
        ('users', '0003_auto_20170606_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Level'),
        ),
    ]
