# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170707_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Bonos', upload_to='uploads/bond/ver_img', verbose_name='Imagen Bonos'),
        ),
    ]
