# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-20 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_auto_20170608_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Numero de nivel ')),
                ('point_xp', models.IntegerField(verbose_name='Experiencia del nivel ')),
                ('point_sm', models.IntegerField(verbose_name='Puntos SM para este nivel ')),
            ],
            options={
                'verbose_name_plural': 'Niveles',
                'ordering': ['number'],
                'verbose_name': 'Nivel',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Titulo de la  tarea')),
                ('type_task', models.CharField(choices=[('bro', 'Bronce'), ('pla', 'Plata'), ('oro', 'Oro')], default='bro', max_length=20, verbose_name=' Tipo de tarea')),
                ('point_exp', models.IntegerField(verbose_name='Experiencia de la tarea')),
                ('SM', models.IntegerField(verbose_name='Puntos SM de esta tarea')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Level', verbose_name='Nivel')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'Tareas',
                'ordering': ['pk'],
                'verbose_name': 'Tarea',
            },
        ),
    ]
