# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_task', models.CharField(choices=[('bro', 'Bronce'), ('pla', 'Plata'), ('oro', 'Oro')], max_length=20)),
                ('point_exp', models.IntegerField()),
                ('SM', models.IntegerField()),
            ],
        ),
    ]
