# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-07 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170607_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Titulo de la  tarea'),
            preserve_default=False,
        ),
    ]
