# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170608_1514'),
        ('games', '0003_task_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
