# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.Level'),
            preserve_default=False,
        ),
    ]
