# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170607_1716'),
        ('games', '0004_task_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
    ]
