# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-15 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_task_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Level', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Producto'),
        ),
    ]
